# -*- coding: utf-8 -*-
"""python-basic-num.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c5mD_gklGIUZJXrcKm8C7CzimK9mfOkB
"""

day=input('yyyy,mm,dd 형식으로 입력하세요  ').split(',')

y,m,d =map(int, day)
print(y,m,d,y-m-d)

#형변환, map 사용
 a,b,c = map(int, input('a b c 입력').split(' '))
 print(a,b,c, a+b+c)
 print(type(a))

#숫자 출력하기 .format()
x=3
y=5
#출력 내용: 3과 5의 합은 8이다.
print (f"{x}과 {y}의 합은 {x+y}이다")

#숫자 출력하기 .format()
x=3
y=5
#출력 내용: 3과 5의 합은 8이다.
print ('{}과 {}의 합은 {}이다'.format(x,y,x+y))

x=3
y=5
#출력 내용: 3과 5의 합은 8이다.
print (str(x)+"과" +str(y)+"의 합은 "+str(x+y)+"이다")

x=3
y=5
#출력 내용: 3과 5의 합은 8이다.
print(x, end='')
print('과 ', end='')
print(y, end='')
print('의 합은 ', end='')
print(x+y, end='')
print('이다.')

#반올림
print(round(3.33))
print(round(3.66))
print(round(3.66,1)) #소수 첫째자리까지 처리함

#절대값
print(abs(3))
print(abs(-3))

#제곱
print(pow(3,2))
print(3**2)

#나눗셈
x,y = divmod(7,2)
print(x) # 몫
print(y)  # 나머지

#최대값
print(max(2,4,5,7,19))
print(min([2,4,5,7,19])) # [] 사용 가능

# 합
print(sum([2,4,5,7,19]))